### ISSUE TITLE
Errors after running import

### ISSUE THREAD

**Issue by nickweisser** [openstream/magento-oscom-migration-tool#4]
I just tried this extension under Magento 1.8.1.0 under MAMP locally, but get an error message when I run the import. After clicking the check requirements button I can enter all the general information, locale selection and import options, but when clicking the start running button it shows a JavaScript popup just saying "error". 

The webserver error log has the following ERR messages:

2013-12-17T21:37:04+00:00 ERR (3): User Error: DDL statements are not allowed in transactions  in /Applications/MAMP/htdocs/magento/1.8/lib/Varien/Db/Adapter/Pdo/Mysql.php on line 408
2013-12-17T21:37:04+00:00 ERR (3): User Error: Some transactions have not been committed or rolled back  in /Applications/MAMP/htdocs/magento/1.8/lib/Varien/Db/Adapter/Pdo/Mysql.php on line 3941
![bildschirmfoto 2013-12-17 um 22 37 14](https://f.cloud.github.com/assets/58966/1768694/4c27a084-6766-11e3-921c-e1f5e68884c6.png)

It worked fine though under 1.7.2.0 on the same MAMP installation for importing categories and products. When trying to import customers and orders the same problems occur as under 1.8.1.0. Same ERR messages and the following in the exception log:

2013-12-17T22:49:15+00:00 ERR (3): 
exception 'Exception' with message '$_FILES array is empty' in /Applications/MAMP/htdocs/magento/1.7/lib/Varien/File/Uploader.php:467
Stack trace:
#0 /Applications/MAMP/htdocs/magento/1.7/lib/Varien/File/Uploader.php(149): Varien_File_Uploader->_setUploadFileId('thumbnail')
#1 /Applications/MAMP/htdocs/magento/1.7/app/code/core/Mage/Catalog/Model/Category/Attribute/Backend/Image.php(57): Varien_File_Uploader->__construct('thumbnail')
#2 [internal function]: Mage_Catalog_Model_Category_Attribute_Backend_Image->afterSave(Object(Mage_Catalog_Model_Category))
#3 /Applications/MAMP/htdocs/magento/1.7/app/code/core/Mage/Eav/Model/Entity/Abstract.php(657): call_user_func_array(Array, Array)
#4 /Applications/MAMP/htdocs/magento/1.7/app/code/core/Mage/Eav/Model/Entity/Abstract.php(1648): Mage_Eav_Model_Entity_Abstract->walkAttributes('backend/afterSa...', Array)
#5 /Applications/MAMP/htdocs/magento/1.7/app/code/core/Mage/Catalog/Model/Resource/Category.php(235): Mage_Eav_Model_Entity_Abstract->_afterSave(Object(Mage_Catalog_Model_Category))
#6 /Applications/MAMP/htdocs/magento/1.7/app/code/core/Mage/Eav/Model/Entity/Abstract.php(1124): Mage_Catalog_Model_Resource_Category->_afterSave(Object(Mage_Catalog_Model_Category))
#7 /Applications/MAMP/htdocs/magento/1.7/app/code/core/Mage/Core/Model/Abstract.php(318): Mage_Eav_Model_Entity_Abstract->save(Object(Mage_Catalog_Model_Category))
#8 /Applications/MAMP/htdocs/magento/1.7/app/code/core/Mage/Oscommerce/Model/Mysql4/Oscommerce.php(264): Mage_Core_Model_Abstract->save()
#9 /Applications/MAMP/htdocs/magento/1.7/app/code/core/Mage/Oscommerce/Model/Mysql4/Oscommerce.php(201): Mage_Oscommerce_Model_Mysql4_Oscommerce->createRootCategory()
#10 /Applications/MAMP/htdocs/magento/1.7/app/code/core/Mage/Oscommerce/controllers/Adminhtml/Oscommerce/ImportController.php(292): Mage_Oscommerce_Model_Mysql4_Oscommerce->createWebsite('1')
#11 /Applications/MAMP/htdocs/magento/1.7/app/code/core/Mage/Core/Controller/Varien/Action.php(419): Mage_Oscommerce_Adminhtml_Oscommerce_ImportController->runAction()
#12 /Applications/MAMP/htdocs/magento/1.7/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('run')
#13 /Applications/MAMP/htdocs/magento/1.7/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#14 /Applications/MAMP/htdocs/magento/1.7/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#15 /Applications/MAMP/htdocs/magento/1.7/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#16 /Applications/MAMP/htdocs/magento/1.7/index.php(87): Mage::run('', 'store')

**Comment by askwhyweb** [comment]
There is also another error I had encountered related to category id as below

[01-Feb-2016 19:39:52 UTC] PHP Fatal error:  Call to a member function getRootCategoryId() on a non-object in /home/xxxx/public_html/magento/app/code/core/Mage/Oscommerce/Model/Mysql4/Oscommerce.php on line 1538

**Comment by nickweisser** [comment]
Thanks for reporting this, you might also need to specify your Magento and PHP versions. Please note, that this module is not under active development and you need to either address this yourself or hope for someone else from the community to have the same problem and fix it for you. Or you hire a developer to fix it and contribute the fix back to this repository (= the community).
